baseURL: https://akirachiku.com
disablePathToLower: true
languageCode: ja-jp
title: 包丁一本さらしに巻いて
hasCJKLanguage: true
pygmentsCodeFences: true
markup:
  defaultMarkdownHandler: "goldmark"
permalinks:
  post: /post/:filename
