baseURL: https://akirachiku.com
disablePathToLower: true
languageCode: ja-jp
title: 包丁一本さらしに巻いて
hasCJKLanguage: true
pygmentsCodeFences: true
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
permalinks:
  post: /post/:filename
